// A CPP program to prompt basic figures
#include <iostream>
using namespace std;
int main()
{
    // Display a box
    cout<<" A BOX "<<endl;
    cout << "*********\n"
      << "*       *\n"
      << "*       *\n"
      << "*       *\n"
      << "*       *\n"
      << "*       *\n"
      << "*       *\n"
      << "*       *\n"
      << "*********\n"<<endl;

    // Display an oval
    cout<<" An OVAL "<<endl;
    cout << "   ***   \n"
      << " *     * \n"
      << "*       *\n"
      << "*       *\n"
      << "*       *\n"
      << "*       *\n"
      << "*       *\n"
      << " *     * \n"
      << "   ***   \n"<<endl;

    // Display an arrow
    cout<<" An ARROW "<<endl;
    cout << "    *    \n"
      << "   ***   \n"
      << "  *****  \n"
      << "    *    \n"
      << "    *    \n"
      << "    *    \n"
      << "    *    \n"
      << "    *    \n"
      << "    *    \n"<<endl;

    // Display a diamond
    cout<< "A DIAMOND "<<endl;
    cout << "    *    \n"
      << "   * *    \n"
      << "  *   *   \n"
      << " *     *  \n"
      << "*       * \n"
      << " *     *  \n"
      << "  *   *   \n"
      << "   * *    \n"
      << "    *    \n";
    // return statement that indicates program terminated successfully
    return 0;
}
